#ifndef MAGIQUE_CONFIG_H
#define MAGIQUE_CONFIG_H

#include <magique/util/Defines.h>


#define MAGIQUE_VERSION "0.0.1"

#if MAGIQUE_DEBUG == 1
//#define MAGIQUE_DEBUG_COLLISIONS
#define MAGIQUE_DEBUG_ENTITIES
#define MAGIQUE_DEBUG_PROFILE
#endif

#define MAGIQUE_DEBUG_ENTITIES
#define MAGIQUE_DEBUG_PROFILE

#define MAGIQUE_MAX_EXPECTED_MAPS 32


#endif //MAGIQUE_CONFIG_H