#ifndef CORECONFIG_H
#define CORECONFIG_H

#include <magique/util/Defines.h>

#if MAGIQUE_DEBUG == 1
//#define MAGIQUE_DEBUG_COLLISIONS
#define MAGIQUE_DEBUG_ENTITIES
#define MAGIQUE_DEBUG_PROFILE
#endif

#define MAGIQUE_DEBUG_ENTITIES
#define MAGIQUE_DEBUG_PROFILE

#define MAGIQUE_MAX_EXPECTED_MAPS 32

#endif //CORECONFIG_H